### ISSUE TITLE
create monsters

### ISSUE THREAD

**Issue by lgmagalhaes88** [lgmagalhaes88/AdventureRPG#18]
create a list of monster to be used in explorations
structure: 

```javascript
  id?: string
  name: string
  level: number
  damage: number
  hp: number
  shield: number
  givedXp: number
  givedGold: number
```

**Comment by hkirschke** [comment]
Firebase DB was released with some new monsters.
Please validate.

**Comment by lgmagalhaes88** [comment]
Same thing in https://github.com/lgmagalhaes88/AdventureRPG/issues/20#issuecomment-429300561
