### ISSUE TITLE
create level progress

### ISSUE THREAD

**Issue by lgmagalhaes88** [lgmagalhaes88/AdventureRPG#19]
create the list of levels. I.E:

<table>
<tr>
<th>level</th>
<th>experience</th>
</tr>
<tr>
<td>1</td>
<td>100</td>
</tr>
<tr>
<td>2</td>
<td>200</td>
</tr>
</table>
...

**Comment by hkirschke** [comment]
Firebase DB was released with some new levels.
Please validate.

**Comment by lgmagalhaes88** [comment]
Same thing for https://github.com/lgmagalhaes88/AdventureRPG/issues/20#issuecomment-429300561
