### ISSUE TITLE
create list of weapons and shields

### ISSUE THREAD

**Issue by lgmagalhaes88** [lgmagalhaes88/AdventureRPG#20]
structure:

Weapon
```javascript
  name: String
  price: number
  damage: number
```
Shield
```javascript
  name: String
  price: number
  defence: number
```

**Comment by hkirschke** [comment]
Firebase DB was released with some new equipment.
Please validate.

**Comment by lgmagalhaes88** [comment]
@hkirschke create equipments in` .json` format in `/data` folder 

![image](https://user-images.githubusercontent.com/19666463/46867681-405ba280-cdfc-11e8-9829-bb6e17213fac.png)
